### ISSUE TITLE
Not really an issue -- Created a list of foreign characters/translations

### ISSUE THREAD

**Issue by eoppe1022** [JosiahParry/geniusR#11]
Using an answer from this:

https://stackoverflow.com/questions/20495598/replace-accented-characters-in-r-with-non-accented-counterpart-utf-8-encoding

And some trial and error with Genius, I compiled a list of foreign characters and how they translate to URLs.

`c("Þ" = "", 
                    "ð" = "", 
                    "Š" = "S", 
                    "š" = "s", 
                    "Ž" = "Z", 
                    "ž" = "z", 
                    "À" = "A", 
                    "Á" = "A", 
                    "Â" = "A", 
                    "Ã" = "A", 
                    "Ä" = "A", 
                    "Å" = "A", 
                    "Æ" = "A", 
                    "Ç" = "C", 
                    "È" = "E",
                    "É" = "E",
                    "Ê" = "E", 
                    "Ë" = "E", 
                    "Ì" = "I", 
                    "Í" = "I", 
                    "Î" = "I", 
                    "Ï" = "I", 
                    "Ñ" = "N", 
                    "Ò" = "O", 
                    "Ó" = "O", 
                    "Ô" = "O", 
                    "Õ" = "O", 
                    "Ö" = "O", 
                    "Ø" = "O", 
                    "Ù" = "U",
                    "Ú" = "U", 
                    "Û" = "U", 
                    "Ü" = "U", 
                    "Ý" = "Y", 
                    "ß" = "Ss", 
                    "à" = "a", 
                    "á" = "a", 
                    "â" = "a", 
                    "ã" = "a", 
                    "ä" = "a", 
                    "å" = "a", 
                    "æ" = "", 
                    "ç" = "c",
                    "è" = "e", 
                    "é" = "e", 
                    "ê" = "e", 
                    "ë" = "e", 
                    "ì" = "i", 
                    "í" = "i", 
                    "î" = "i", 
                    "ï" = "i", 
                    "ñ" = "n", 
                    "ò" = "o", 
                    "ó" = "o", 
                    "ô" = "o", 
                    "õ" = "o",
                    "ö" = "o", 
                    "ø" = "o", 
                    "ù" = "u", 
                    "ú" = "u", 
                    "û" = "u", 
                    "ý" = "y")`

**Comment by JosiahParry** [comment]
Thanks for this! But unfortunately this isn't going to work with genius. Take a look at this issue https://github.com/JosiahParry/geniusR/issues/3. the ø is replaced with nothing.

**Comment by eoppe1022** [comment]
Interesting. Try running `options(encoding = "UTF-8")` prior to re-setting `prep_info()` it works for me there (though in that list, I have it so ø = o)
