### ISSUE TITLE
Difficulty in Processing "Verified Commentary"

### ISSUE THREAD

**Issue by eoppe1022** [JosiahParry/geniusR#12]
Check out the output from this:

https://genius.com/Fleet-foxes-third-of-may-odaigahara-lyrics

```> genius_url("https://genius.com/Fleet-foxes-third-of-may-odaigahara-lyrics")
# A tibble: 55 x 3
   track_title               lyric                                         line
   <chr>                     <chr>                                        <int>
 1 Third of May / Ōdaigahara Light ended the night, but the song remained     1
 2 Third of May / Ōdaigahara "And I was "                                     2
 3 Third of May / Ōdaigahara hiding by the stair                              3
 4 Third of May / Ōdaigahara half here                                        4
 5 Third of May / Ōdaigahara Half there                                       5
 6 Third of May / Ōdaigahara ", past the "                                    6
 7 Third of May / Ōdaigahara lashing rain                                     7
 8 Third of May / Ōdaigahara "And as the "                                    8
 9 Third of May / Ōdaigahara " would "                                        9
10 Third of May / Ōdaigahara petal white                                     10
# ... with 45 more rows
```

I'm not sure if this is consistent, but I thought I'd bring it up.

**Comment by JosiahParry** [comment]
Shoot. This is a problem causes from the annotation. The annotations are in a `<p>` tag, not a `<span>` tag. This makes it `genius_url()` think it's a new line.

On line 8 of the tibble, `sky[e]` is omitted because of the bracket. I currently have the function written so that lines with brackets are omitted. This is because they tend to be things like guest vocals or instrumentation etc.

**Comment by eoppe1022** [comment]
I'm gonna do some investigating, but I'm guessing if the set of brackets is on it's own line, it should always be omitted.

There's probably some regex for this. 

Also, this is less robust but you could do something like:

*Omit* and skip line if characters between [] > 3 or includes ?, !, or other punct. 

*else* delete brackets and contents but maintain line structure

**Comment by JosiahParry** [comment]
fixed in pr https://github.com/JosiahParry/geniusR/pull/24
