### ISSUE TITLE
update genius_album to handle "features" to the info argument

### ISSUE THREAD

**Issue by JosiahParry** [JosiahParry/geniusR#21]
PR https://github.com/JosiahParry/geniusR/pull/20 enabled the value `"features"` to the `genius_url()` function. This precipitates through to `genius_album()`. There is now a duplicated column `track_title`. 

See below for an example: 

```
DAMN <- genius_album(artist = "Kendrick Lamar", album = "DAMN.", info = "features")
```

**Comment by JosiahParry** [comment]
@natebarr64 if you want to try and take a stab at this go ahead.

**Comment by natebarr64** [comment]
Thanks for the pull! I did a quick fix by removing track titles in the "features" switch of genius_url. 

Bumped into another error with parsing some albums. This input:
```
Doris <- genius_album(artist = "Earl Sweatshirt", album = "Doris", info = "features")
```

leads to: 

```
Error in mutate_impl(.data, dots) : 
  Evaluation error: Evaluation error: object 'lyric' not found.. 
```
Ill try to figure this out when I get a chance.

**Comment by JosiahParry** [comment]
This error is caused by a song with no lyrics. https://genius.com/Earl-sweatshirt-523-lyrics

The only text is `"[Produced by RandomBlackDude]"`. The spread is causing the error.

**Comment by JosiahParry** [comment]
Looks like a potential work around is to bind a row to the data frame if its empty for good measure then filter out that row

**Comment by JosiahParry** [comment]
Fixed in https://github.com/JosiahParry/geniusR/pull/24
