### ISSUE TITLE
genius_lyrics retrieves singer for each verse as lyrics

### ISSUE THREAD

**Issue by dgruenew** [JosiahParry/geniusR#4]
Just tried this for the following:

```
raw_df <- geniusR::genius_lyrics(artist = "Pink Floyd",
                                 song = "Comfortably Numb",
                                 info = "all")
```
Which gives the singer "Roger Waters" as the very first lyric.  "David Gilmour" is recorded as well for line 14.

(very cool package by the way!)

**Comment by JosiahParry** [comment]
Hm. Interesting. I thought I solved the bracket issue! I'll be sure to give this a look. Thank you!

**Comment by JosiahParry** [comment]
fixed in pr https://github.com/JosiahParry/geniusR/pull/24
