### ISSUE TITLE
genius_url() not working propperly

### ISSUE THREAD

**Issue by LukasLoTo** [JosiahParry/geniusR#62]
In the tutorial code you mention that, if the lyrics are not found, to use a combination of **genius_tracklist()** and **genius_url()**. Sometimes when using **genius_url()** you get **"Error in stream$next_ident() : Expected ident, got <EOF at 2>"** , and you have to execute the line of code several times before it works, which suggests maybe its an error outside of the syntax or the data manipulation itself. 
![image](https://user-images.githubusercontent.com/87031043/131181466-2c9ba876-1dca-4906-b238-bc2ad71f8c85.png)
![image](https://user-images.githubusercontent.com/87031043/131181536-e6ebb6e6-c60a-41a6-9952-98d1308230c7.png)
The last error is the one where I got to finally create the object and the error stopped. After that i can use the variable without further errors.
The number of times you have to re-run the code seems to decrease if the genius_url function is right below the previus one, no line jump.

**Comment by LukasLoTo** [comment]
Thank you for the clarification and the quick reply :) 
I'm using version 4.1.1. What I was working on is the following:
`CA1 = genius_tracklist(artist = "Soda Stereo", album = "Cancion animal") %>% 
  filter(track_title == "(En) El Séptimo Día")
ElSeptimoDia = genius_url(CA1$track_url)`
It's the same as the screenshot though, I'm not sure if that's what you were asking for. Wasn't using any additional files or libraries other than genius.

**Comment by JosiahParry** [comment]
Please see the reprex package for more https://reprex.tidyverse.org. 

An example that I can run that will produce the error each time is what is needed.

**Comment by LukasLoTo** [comment]
My bad. I'm fairly new to R and programming in general. 
``` r
library(genius)
library(reprex)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

CA1 = genius_tracklist(artist = "Soda Stereo", album = "Cancion animal") %>% 
  filter(track_title == "(En) El Séptimo Día")
ElSeptimoDia = genius_url(CA1$track_url)
#> Error in stream$next_ident(): Expected ident, got <EOF at 2>
```

<sup>Created on 2021-08-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by LukasLoTo** [comment]
``` r
CA1 = genius_tracklist(artist = "Soda Stereo", album = "Cancion animal") %>% 
  filter(track_title == "(En) El Séptimo Día")
ElSeptimoDia = genius_url(CA1$track_url)
```

<sup>Created on 2021-08-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by JosiahParry** [comment]
Your example works for me.

**Comment by LukasLoTo** [comment]
It's been back and forth. Today its showing little to no error showing to me aswell, but yesterday as the screenshots show I got plenty of them. Then if you got no error it might be due to connection problems or something like that. I'll let you know if I find anything else related. Thanks again.
