### ISSUE TITLE
stream$next_ident()

### ISSUE THREAD

**Issue by redapemusic35** [JosiahParry/geniusR#65]
This may be related to https://github.com/JosiahParry/geniu
![Screenshot_20211208_171641](https://user-images.githubusercontent.com/23493710/145306598-be857725-a6d7-4495-91c1-08104fed4517.png)
s/issues/62, but the suggestion did not solve my issue.
![Screenshot_20211208_171710](https://user-images.githubusercontent.com/23493710/145306603-9455aeae-240a-4342-88bf-a73a7d89dfb5.png)

**Comment by JosiahParry** [comment]
I'm sorry there is not any information in this issue. Further, this package is no longer supported.
